### Login
POST https://3030-quiet-sunset-73461303.in-ws1.runcode.io/auth/login
Content-Type: application/json

{
  "payload": {
    "password": "<PASSWORD>"
    "email": "emily@example.com"
  }
}

### Get Card Data
GET https://3030-quiet-sunset-73461303.in-ws1.runcode.io/card
