### Login
POST https://f-u-s-e.onrender.com/auth/login
Content-Type: application/json

{
  "payload": {
    "password": "<PASSWORD>"
    "email": "emily@example.com"
  }
}

### Get Card Data
GET https://f-u-s-e.onrender.com/card
